### ISSUE TITLE
Jar file not working

### ISSUE THREAD

**Issue by tanlongbin** [robytanama/duke#11]
@robytanama All your iP peer reviewers reported that they could not get the JAR file to work. I tried it myself and it didn’t work on my computer either. This means we are unable to grade your iP.

This is what is displayed when I run the JAR file, with presumably an error message : 
![image](https://user-images.githubusercontent.com/36988050/67155977-5a06c280-f34b-11e9-879f-83cbdeab191e.png)
Your Jar is likely to be compiled using Java 12. 

Please release a new version that is cross-platform and confirmed to work with Java 11. When it is ready, post here to let me know ASAP (deadline: a week from today).

**Comment by robytanama** [comment]
hi, i have attached a new version of the Jar file, please do inform me if it's still not working

**Comment by tanamaroby** [comment]
The new release is tagged under 1.1 @tanlongbin

**Comment by tanamaroby** [comment]
@tanlongbin do i have to create new release?

**Comment by tanlongbin** [comment]
It's ok. I've tested the new release and it works. Thank you!
